CREATE TABLE Members
(
MemberId INT IDENTITY PRIMARY KEY,
Email NVARCHAR(256) NOT NULL,
Password NVARCHAR(128) NOT NULL,
FirstName NVARCHAR(128) NOT NULL,
LastName NVARCHAR(128) NOT NULL,
)

CREATE TABLE Bots
(
BotId INT IDENTITY PRIMARY KEY,
MemberId INT REFERENCES Members(MemberId),
ChannelToken NVARCHAR(256) NOT NULL,
ChannelSecret NVARCHAR(256) NOT NULL
)

CREATE TABLE Messages
(
MessageId INT IDENTITY PRIMARY KEY,
BotId INT REFERENCES Bots(BotId),
Event INT NOT NULL,
Type INT NOT NULL,
KeyWord NVARCHAR(256) NOT NULL,
ImageUrl NVARCHAR(256),
Url NVARCHAR(256),
Yes NVARCHAR(256),
No NVARCHAR(256),
Msg NVARCHAR(256),
PostBack NVARCHAR(256),
Title NVARCHAR(256),
STKId NVARCHAR(3),
STKPKGId NVARCHAR(3),
Address NVARCHAR(256),
Latitude Float,
Longitude Float,
Text NVARCHAR(500),
)